### ISSUE TITLE
Replay to database with another name

### ISSUE THREAD

**Issue by fvanderhaegen** [spaghettidba/WorkloadTools#80]
I'm trying to replay a workload to a database with name that is different from the source database.
The workload has been captured in a sqllite file.

When I check the source code of the ReplayWorker I found following code snippet:
` if (conn.Database != command.Database)
{
                   logger.Trace($"Worker [{Name}] - Changing database to {command.Database} ");
                    conn.ChangeDatabase(command.Database);
}`

When the databasename of the connection doesn't match the name of the database in the sqllite file it is changed.

Is there a reason why a workload can't be replayed on a database with a different name?

**Comment by spaghettidba** [comment]
Hi, the reason is because the source workload could be coming from multiple databases. If you capture a workload on database A and database B, when you replay it what you want is each command replayed against its respective database.
Ostress solved this issue using a map of database id/database name. I could probably do something similar here, like having a map of databases and the desired target database during the replay. 
Would that work for you? In case please open an issue and I'll be glad to code a solution for you.

**Comment by fvanderhaegen** [comment]
Oh, now I understand this better. I'll also first explain what I try to do.

I've a database on a AG and I'll want to test some changes before I'll put them in production.
So I restored the database on the secondary/passive replica as another database.
Now I want to replay the workload and analyze the performance but the queries are al pointed to the non-readable database.

The solution you propose would solve the issue for me.

Thanks

**Comment by spaghettidba** [comment]
OK, I'll try to implement it ASAP
